app/src/main/java/tech/relaycorp/gateway/domain/endpoint/EndpointRegistration.kt
app/src/test/java/tech/relaycorp/gateway/domain/endpoint/EndpointRegistrationTest.kt

I had to increase it to 15 seconds just because it was breaking an instrumentation test but #88 should make it possible to go back to the original 5 seconds.

fix: Decrease Client Registration Authorisation validity period to 5 sec

---

app/build.gradle
app/src/main/java/tech/relaycorp/gateway/domain/courier/CargoCollection.kt
app/src/main/java/tech/relaycorp/gateway/domain/courier/CargoDelivery.kt

Because of https://github.com/grpc/grpc-java/issues/7385
TODO:

fix(CogRPC): Use OkHTTP instead of Netty

---

app/build.gradle

This change will allow the Android GW to (de)encrypt cargo exchanged with the public gateway. See: https://github.com/relaycorp/relayverse/issues/16
The counterpart to this change will land on the server in a few minutes: https://github.com/relaycorp/relaynet-internet-gateway/pull/299

fix: Upgrade Relaynet library to use AES-CBC

---

app/src/main/java/tech/relaycorp/gateway/background/ConnectionStateObserver.kt

In order to minimise the risk of Google marking these requests as malicious, minimise reliance on Google and minimise the data Google gets about our users.

fix: Only ping Google if we can't reach the public gateway

---

app/src/main/res/layout/activity_courier_connection.xml

Fixes #243.
I don't fully understand what I'm doing, but I noticed these two lines I'm removing aren't used by the other two items on the list. And the alignment issue seems fixed.

fix: Align text when syncing with courier

---

app/src/main/java/tech/relaycorp/gateway/background/CheckPublicGatewayAccess.kt
app/src/main/java/tech/relaycorp/gateway/background/PingRemoteServer.kt

Because we get a ton of those when the device is disconnected from the Internet, and it makes it hard to keep up with the logs when troubleshooting.

chore: Remove traceback from ping failure logs

---

app/src/androidTest/java/tech/relaycorp/gateway/background/endpoint/EndpointPreRegistrationServiceTest.kt
app/src/main/java/tech/relaycorp/gateway/App.kt
app/src/main/java/tech/relaycorp/gateway/data/disk/SensitiveStore.kt
app/src/main/java/tech/relaycorp/gateway/domain/LocalConfig.kt
app/src/main/java/tech/relaycorp/gateway/domain/courier/CalculateCRCMessageCreationDate.kt
app/src/test/java/tech/relaycorp/gateway/domain/LocalConfigTest.kt

The problem here is that the certificate's start date was always later than the CCA's or the cargo's (whose creation time is 90 mins in the past).
I'm proposing to fix this by creating this certificate upfront, along with its key pair.
Fixes https://github.com/relaycorp/relaynet-courier-android/issues/277

fix: Self-issue certificate when app is used for the first time

---

.github/data/firebase-test-lab.yml

Firebase Test Lab doesn't seem to support Huawei P8 lite any more.

chore(CI): Replace Huawei P8 lite with Asus Nexus 7

---

app/build.gradle
app/src/main/java/tech/relaycorp/gateway/pdc/local/routes/ParcelDeliveryRoute.kt
app/src/test/java/tech/relaycorp/gateway/pdc/local/routes/ParcelDeliveryRouteTest.kt

See:
- https://github.com/relaycorp/awala-poweb-jvm/pull/130
- https://github.com/AwalaNetwork/specs/commit/f4ef055baa67e1808efdb63be644592e5c052646

fix: Use "422 Unprocessable Entity" when server refuses parcel

---

app/src/main/java/tech/relaycorp/gateway/pdc/local/PDCServer.kt

I'm currently abusing this to debug #411, so this PR should be merged afterwards.

fix: Restrict PDC server to clients on the same device

---

.github/workflows/ci-cd.yml
app/build.gradle
app/src/main/AndroidManifest.xml
gradle.properties

Related with: relaycorp/awala-ping-android#158
Changes made to Package Visibility and security with Android 11.
https://developer.android.com/training/package-visibility/declaring#package-name
In this PR you can also see some changes to compile to Android 12, and Mac M1

fix: Android 11 binding issue

---

app/build.gradle
app/src/main/java/tech/relaycorp/gateway/data/preference/PublicGatewayPreferences.kt
app/src/main/java/tech/relaycorp/gateway/domain/courier/ProcessCargo.kt
app/src/main/java/tech/relaycorp/gateway/domain/courier/RotateCertificate.kt
app/src/test/java/tech/relaycorp/gateway/domain/courier/ProcessCargoTest.kt
app/src/test/java/tech/relaycorp/gateway/domain/courier/RotateCertificateTest.kt

feat: Rotate certificate from courier

---

app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt
app/src/test/java/tech/relaycorp/gateway/domain/courier/GenerateCCATest.kt

The one issued by the public gateway.
This is needed so that we can fix https://github.com/relaycorp/relaynet-internet-gateway/issues/53

fix: Generate CCA with correct sender's certificate

---

app/src/main/java/tech/relaycorp/gateway/data/disk/CargoStorage.kt
app/src/main/java/tech/relaycorp/gateway/domain/LocalConfig.kt
app/src/test/java/tech/relaycorp/gateway/data/disk/CargoStorageTest.kt
app/src/test/java/tech/relaycorp/gateway/domain/LocalConfigTest.kt
app/src/test/java/tech/relaycorp/gateway/domain/courier/GenerateCCATest.kt
app/src/test/java/tech/relaycorp/gateway/domain/courier/GenerateCargoTest.kt
app/src/test/java/tech/relaycorp/gateway/domain/endpoint/EndpointRegistrationTest.kt
app/src/test/java/tech/relaycorp/gateway/domain/publicsync/CollectParcelsFromGatewayTest.kt
app/src/test/java/tech/relaycorp/gateway/domain/publicsync/DeliverParcelsToGatewayTest.kt
app/src/test/java/tech/relaycorp/gateway/domain/publicsync/RegisterGatewayTest.kt

feat: Renew Cargo Delivery Authorisation

---

app/build.gradle
app/lint.xml
app/src/main/AndroidManifest.xml
app/src/main/java/tech/relaycorp/gateway/ui/BaseActivity.kt
app/src/main/java/tech/relaycorp/gateway/ui/settings/MigrateGatewayViewModel.kt
app/src/main/java/tech/relaycorp/gateway/ui/sync/CourierSyncViewModel.kt
app/src/main/res/xml/data_extraction_old_rules.xml
app/src/main/res/xml/data_extraction_rules.xml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Part of https://github.com/relaycorp/relayverse/issues/39

fix(deps): Update dependencies (Kotlin 1.6)

---

app/build.gradle
app/src/main/java/tech/relaycorp/gateway/data/preference/InternetGatewayPreferences.kt
app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt
app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCargo.kt
app/src/test/java/tech/relaycorp/gateway/domain/courier/GenerateCCATest.kt
app/src/test/java/tech/relaycorp/gateway/domain/courier/GenerateCargoTest.kt

We were still using URLs.
Also upgrade gRPC deps to fix other issues that prevented me from testing this fix.

fix(CogRPC): Use Internet address as recipient when producing parcels

---

app/src/main/java/tech/relaycorp/gateway/domain/publicsync/CollectParcelsFromGateway.kt

fix: Omit stack trace in log for parcel collection retry

---

app/build.gradle

So we can get this fix: https://github.com/relaycorp/awala-poweb-jvm/pull/282

fix(deps): Upgrade PoWeb library to v1.5.54

---

app/src/main/java/tech/relaycorp/gateway/App.kt
app/src/main/java/tech/relaycorp/gateway/StrictModeSetup.kt

Closes #708
The allow list will need more fine-tuning. @gnarea You will need to get your stacktraces there to get this working for you.
For devices lower than Android P, StrictMode will no longer crash, just log issues.

fix: Introduce allow list in StrictMode

---

app/src/main/java/tech/relaycorp/gateway/background/PingRemoteServer.kt
app/src/main/java/tech/relaycorp/gateway/data/doh/ResolveServiceAddress.kt

Fixes #717
We're repeating the connection state check every 5 seconds. But the 3 checks themselves did not have timeouts, so that meant it could take several minutes just to complete one check. I've now capped each check to 5 seconds as well, so worse case scenario it could take 20 seconds between connection state checks.

fix: Improve connection state checks speed

---

app/src/main/java/tech/relaycorp/gateway/App.kt
app/src/main/java/tech/relaycorp/gateway/domain/publicsync/PublicSync.kt
app/src/main/java/tech/relaycorp/gateway/domain/publicsync/RegisterGateway.kt
app/src/test/java/tech/relaycorp/gateway/domain/publicsync/PublicSyncTest.kt

Closes #714
Also fixes 2 issues I found:
- Certificates weren't deleted if expired, because that method was called after the never-ending public sync method
- The gateway certificate we received expires after 30 days, and we were always renewing them if the expiration date was less than 90 days (changed to 25 days)

fix: Register gateway on sync

---

app/src/androidTest/java/tech/relaycorp/gateway/background/endpoint/EndpointPreRegistrationServiceTest.kt
app/src/androidTest/java/tech/relaycorp/gateway/background/endpoint/GatewaySyncServiceParcelCollectionTest.kt
app/src/androidTest/java/tech/relaycorp/gateway/background/endpoint/GatewaySyncServiceParcelDeliveryTest.kt
app/src/androidTest/java/tech/relaycorp/gateway/test/TestApp.kt
app/src/main/java/tech/relaycorp/gateway/App.kt
app/src/main/java/tech/relaycorp/gateway/AppModule.kt
app/src/main/java/tech/relaycorp/gateway/domain/publicsync/PublicSync.kt
app/src/main/java/tech/relaycorp/gateway/pdc/local/PDCServer.kt
app/src/main/java/tech/relaycorp/gateway/pdc/local/routes/ParcelCollectionRoute.kt

Addresses https://github.com/relaycorp/relaynet-gateway-android/issues/724
The other task needed to close this ticket is to have endpoint apps bind and unbind from the Gateway when they are in the foreground/background.

fix: Don't do network calls when apps are in background

---

app/src/androidTest/java/tech/relaycorp/gateway/background/endpoint/EndpointPreRegistrationServiceTest.kt
app/src/main/java/tech/relaycorp/gateway/background/endpoint/EndpointPreRegistrationService.kt

Related with https://github.com/relaycorp/relaynet-gateway-android/pull/726

fix: Endpoint pre-registration should return GATEWAY_NOT_REGISTERED if gateway's certificate is expired

---

app/build.gradle
app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCargo.kt
app/src/test/java/tech/relaycorp/gateway/domain/courier/GenerateCargoTest.kt

Which is the limit. When exceeded, an exception is thrown.
TODO:

fix: Cap generated cargo TTL at 180 days
